# This file defines the default configuration for the entire `rust-lang` organization.
#
# The available configuration options and features are the same as those in the `triagebot.toml` repository,
# except that each configuration entry can include an `excluded-repos = ["rust-lang/foo"]` option.

# Adds a "View changes since this review" link at the end of a review body to view
# the changes that happened since the review
# Documentation at: https://forge.rust-lang.org/triagebot/review-changes-since.html
[review-changes-since]

# Adds a comment linking to triagebot range-diff viewer when a PR is rebased
# onto a different base commit
# Documentation at: https://forge.rust-lang.org/triagebot/range-diff.html
[range-diff]

# Enable issue transfers within the org
# Documentation at: https://forge.rust-lang.org/triagebot/transfer.html
[transfer]

# Enable manual assignments in PRs using `r? name`
# Documentation at: https://forge.rust-lang.org/triagebot/pr-assignment.html
[assign]
warn_non_default_branch = true

# Enable merge conflicts notifications in PRs
# Documentation at: https://forge.rust-lang.org/triagebot/merge-conflicts.html
[merge-conflicts]
excluded-repos = [
  "rust-lang/team", # no write permissions 
  "rust-lang/rust", # handled by bors
]
