[relabel]
allow-unauthenticated = ["bug", "invalid", "question", "enhancement"]

[assign]

[ping.wg-meta]
message = """\
This is just testing some functionality, please ignore this ping.
"""
label = "help wanted"
